### ISSUE TITLE
OPRA?

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#1]
I added the two PDFs on the site now to the data/pdfs dir. If we collect them each month, by November, we'll have continuous monthly data back to Dec. 2013. 

Is it worth it to reach out to NJSP and see how far back we can easily get the monthly PDFs? When did they start doing that?

And if they won't give them to us, should we OPRA them?

**Comment by sstirling** [comment]
They started doing this in the late-winter, early-spring of 2013.  I can ping Steve Jones and see if he'll grab them for us.  Although, the monthly reports are preliminary and do change (2014's files were updated as recently as Friday), so I'm not sure if we should rely on monthly data if we have more final historical data available.

**Comment by tommeagher** [comment]
@sstirling, ask if we can get all the monthly reports back since they started doing them. If he balks, we should at least try to OPRA them. 
If he's game, ask if we can get them in Excel instead of PDF and if they'd post them each month in Excel. The worst that will happen is he'll say no.

**Comment by sstirling** [comment]
I'll call Jones in the morning and see what we can do.

**Comment by sstirling** [comment]
@tommeagher  I'm a schlub so I forgot to do this. I'll set myself an alert to do it Monday.

**Comment by sstirling** [comment]
Jones said he doesn't believe they have historic ones around for the weekly/monthly stats since they're updated with finalized information in the annuals.  I'm skeptical of that and we could always try to OPRA them if we want.  But he said the files are updated weekly.  

He said the information is only in the proprietary format you see it in at the moment, but they may export in other formats in the future.  

Additionally, annuals are still being put out by NJSP.  2013 should drop shortly.

**Comment by tommeagher** [comment]
It would be more ideal to be able to do monthly totals back, but I think if we can get 2014 and 2015 for now by grabbing these monthly, it's a good place to start. 
Unless @sstirling or @CarlaAstudillo are really itching to launch an OPRA battle for these, let's table it for now.

**Comment by tommeagher** [comment]
So, we'll say that we're going to compile monthly crime report data for 2015, going forward. Over the course of this year, we'll also pick up each month's 2014 data and add that to the database. Closing this discussion for now.
