### ISSUE TITLE
Help test first draft of script

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#7]
@CarlaAstudillo and @sstirling, can you take a few minutes to read the README and test the csver.rb script on your machine? 

There's no rush on this, but it's a functioning first draft that works on my machine. I just need help breaking it and isolating issues to fix and improve it.

**Comment by tommeagher** [comment]
Also, this script appears to work for both monthly and annual reports. It needs a little bit of tweaking to function entirely properly for the annuals (ie - #9), but any and all bugs you spot, or features you'd like to see, I'd love to hear 'em.

**Comment by CarlaAstudillo** [comment]
Tested it. The only error I got was it didn't find pdftk (because I didn't have it installed in my computer).

But once I installed pdftk, it worked for both monthly and annual. I think the naming convention for the annual numbers (https://github.com/HackJersey/crime/issues/9) is fine.

I guess the only thing I would say is make sure to tell users to have pdftk installed, although if you're thinking of removing docsplit (see https://github.com/HackJersey/crime/issues/15), then I'm guessing it's not really an issue anymore?

**Comment by tommeagher** [comment]
Thanks, Carla! This is super helpful. 
I closed #15, so pdftk shouldn't be a problem any more. If you have any other thoughts on command line options you'd be interested in using, in addition to the ones I've listed so far in #11, please let me know.

**Comment by tommeagher** [comment]
Also, adding @esagara to this thread in case he wants to kick the tires on this and chime in with some more helpful advice.

**Comment by tommeagher** [comment]
Officially made this a public beta release today: https://github.com/HackJersey/crime/tree/v0.1.0
Still eager for any and all feedback on the script, but will turn my attention to the data pipeline now.

**Comment by tommeagher** [comment]
Closing this issue. If you spot anything we need to address, or have any ideas for improvements, please add an issue.
